version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: traffic_share
      POSTGRES_USER: traffic_user
      POSTGRES_PASSWORD: traffic_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://traffic_user:traffic_pass@postgres:5432/traffic_share
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-change-in-production
      - DEBUG=False
    depends_on:
      - postgres
      - redis
    command: python -m uvicorn traffic_share.server.main:app --host 0.0.0.0 --port 8000

volumes:
  postgres_data:
  redis_data:
